### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by dephiros** [flareact/flareact#20]
Just saw this project this morning and I have been looking for this for a while as a cloudflare/next user. Thank you for the work

Do we have built-in typescript support similar to next?

**Comment by jplhomer** [comment]
Not yet, but I think it would be nice to add! May require the user to install `typescript` as a peer dependency, since Flareact is not written with Typescript. I presume we could add it in here as a default loader: https://github.com/flareact/flareact/blob/canary/configs/webpack.config.js

In the meantime, I'm hoping you can add Typescript support in a [custom webpack config](https://flareact.com/docs/custom-webpack-config).

**Comment by jplhomer** [comment]
Preliminary TypeScript support has landed in the `alpha` channel 🎉 

https://flareact.com/docs/typescript
https://github.com/flareact/flareact/tree/canary/examples/with-typescript
